/* Elijah JavaScript Collection Library v0.4 Copyright 2013 Simon P Chang. */
(function(){function g(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.uber=b.prototype}Object.prototype.toString=function(){var a=[],b;for(b in this)a.push(b+":"+(null===this[b]?"null":this[b].toString()));return"{"+a.join(",")+"}"};Array.prototype.toString=function(){var a=[],b;for(b in this)a.push(null===this[b]?"null":this[b].toString());return"["+a.join(",")+"]"};Date.prototype.toString=function(){return this.getMonth()+1+"/"+this.getDate()+"/"+this.getFullYear()+
" "+this.getHours()+":"+this.getMinutes()+":"+this.getSeconds()+"."+this.getMilliseconds()};String.prototype.toString=function(){return"'"+this+"'"};var f=function(){this._ctn};f.prototype={toString:function(){return this._ctn.toString()}};var e=function(){f.apply(this,arguments);this._ctn=[]};g(e,f);e.prototype={size:function(){return this._ctn.length},clear:function(){this._ctn=[]},set:function(a){void 0!==a&&this._ctn.push(a)},setRange:function(a){a instanceof Array&&a.length?this._ctn=this._ctn.concat(a):
a instanceof List&&(a.size&&a.size())&&(this._ctn=this._ctn.concat(a._ctn))},contains:function(a){return-1!==this._ctn.indexOf(a)},empty:function(){return 0===this._ctn.length},toArray:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);return a},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(b,this._ctn[b]))break},toString:e.uber.toString};var h=function(){f.apply(this,arguments);this._ctn={};this._size=0};g(h,f);h.prototype={toString:h.uber.toString};var c=
function(a){e.apply(this,arguments);this.setRange(a)};g(c,e);c.prototype={size:c.uber.size,clear:c.uber.clear,set:c.uber.set,get:function(a){return this._ctn[a]},setRange:c.uber.setRange,contains:c.uber.contains,indexOf:function(a){return this._ctn.indexOf(a)},lastIndexOf:function(a){return this._ctn.lastIndexOf(a)},indicesOf:function(a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(parseInt(c,10));return b},empty:c.uber.empty,removeAt:function(a){0<=a&&a<this._ctn.length&&this._ctn.splice(a,
1)},remove:function(a){this.removeAt(this.indexOf(a))},removeLast:function(a){this.removeAt(this.lastIndexOf(a))},removeAll:function(a){if(void 0===a)this.clear();else for(var b=this._ctn.length-1;0<=b;b--)this._ctn[b]===a&&this.removeAt(b)},reverse:function(){this._ctn.reverse()},toArray:c.uber.toArray,each:c.uber.each,toString:c.uber.toString};var j=function(){h.apply(this,arguments)};g(j,f);j.prototype={size:function(){return this._size},clear:function(){this._ctn={};this._size=0},set:function(a,
b){void 0!==a&&void 0!==b&&(void 0===this._ctn[a]&&this._size++,this._ctn[a]=b)},get:function(a){return this._ctn[a]},getByValue:function(a){if(void 0!==a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(c);return b}},containsKey:function(a){for(var b in this._ctn)if(b===a)return!0;return!1},containsValue:function(a){for(var b in this._ctn)if(this._ctn[b]===a)return!0;return!1},remove:function(a){void 0!==a&&(delete this._ctn[a],this._size--)},removeByValue:function(a){for(var b in this._ctn)this._ctn[b]===
a&&this.remove(b)},empty:function(){return 0===this._size},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(b,this._ctn[b]))break},keys:function(){var a=[],b;for(b in this._ctn)a.push(b);return a},values:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);return a},toString:j.uber.toString};var d=function(a){e.apply(this,arguments);this.pushRange(a)};g(d,e);d.prototype={size:d.uber.size,clear:d.uber.clear,push:d.uber.set,pop:function(){return this._ctn.pop()},pushRange:d.uber.setRange,
peek:function(){return this._ctn[this._ctn.length-1]},contains:d.uber.contains,empty:d.uber.empty,toArray:function(){for(var a=[],b=this._ctn.length-1;0<=b;b--)a.push(this._ctn[b]);return a},each:function(a){if("function"===typeof a)for(;!this.empty()&&!1!==a(this.pop()););},toString:d.uber.toString};window.List=c;window.Map=j;window.Stack=d})();
