/* Elijah JavaScript Collection Library v0.5 Copyright 2013 Simon P Chang. */
(function(){function g(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.uber=b.prototype}Object.prototype.toString=function(){var a=[],b;for(b in this)a.push(b+":"+(null===this[b]?"null":this[b].toString()));return"{"+a.join(",")+"}"};Array.prototype.toString=function(){var a=[],b;for(b in this)a.push(null===this[b]?"null":this[b].toString());return"["+a.join(",")+"]"};Date.prototype.toString=function(){return this.getMonth()+1+"/"+this.getDate()+"/"+this.getFullYear()+
" "+this.getHours()+":"+this.getMinutes()+":"+this.getSeconds()+"."+this.getMilliseconds()};String.prototype.toString=function(){return"'"+this+"'"};var h=function(){this._ctn};h.prototype={toString:function(){return this._ctn.toString()}};var f=function(){h.apply(this,arguments);this._ctn=[]};g(f,h);f.prototype={size:function(){return this._ctn.length},clear:function(){this._ctn=[]},set:function(a){void 0!==a&&this._ctn.push(a)},setRange:function(a){a instanceof Array&&a.length?this._ctn=this._ctn.concat(a):
a instanceof List&&(a.size&&a.size())&&(this._ctn=this._ctn.concat(a._ctn))},contains:function(a){return-1!==this._ctn.indexOf(a)},empty:function(){return 0===this.size()},toArray:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);return a},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(b,this._ctn[b]))break},toString:f.uber.toString};var j=function(){h.apply(this,arguments);this._ctn={};this._size=0};g(j,h);j.prototype={toString:j.uber.toString};var c=function(a){f.apply(this,
arguments);this.setRange(a)};g(c,f);c.prototype={size:c.uber.size,clear:c.uber.clear,set:c.uber.set,get:function(a){return this._ctn[a]},setRange:c.uber.setRange,contains:c.uber.contains,indexOf:function(a){return this._ctn.indexOf(a)},lastIndexOf:function(a){return this._ctn.lastIndexOf(a)},indicesOf:function(a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(parseInt(c,10));return b},empty:c.uber.empty,removeAt:function(a){0<=a&&a<this.size()&&this._ctn.splice(a,1)},removeRange:function(a,
b){0<=a&&a<b&&this._ctn.splice(a,b-a)},remove:function(a){this.removeAt(this.indexOf(a))},removeLast:function(a){this.removeAt(this.lastIndexOf(a))},removeAll:function(a){if(void 0===a)this.clear();else for(var b=this.size()-1;0<=b;b--)this._ctn[b]===a&&this.removeAt(b)},reverse:function(){this._ctn.reverse()},toArray:c.uber.toArray,each:c.uber.each,toString:c.uber.toString};var k=function(){j.apply(this,arguments)};g(k,h);k.prototype={size:function(){return this._size},clear:function(){this._ctn=
{};this._size=0},set:function(a,b){void 0!==a&&void 0!==b&&(void 0===this._ctn[a]&&this._size++,this._ctn[a]=b)},get:function(a){return this._ctn[a]},getByValue:function(a){if(void 0!==a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(c);return b}},containsKey:function(a){for(var b in this._ctn)if(b===a)return!0;return!1},containsValue:function(a){for(var b in this._ctn)if(this._ctn[b]===a)return!0;return!1},remove:function(a){void 0!==a&&(delete this._ctn[a],this._size--)},removeByValue:function(a){for(var b in this._ctn)this._ctn[b]===
a&&this.remove(b)},empty:function(){return 0===this._size},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(b,this._ctn[b]))break},keys:function(){var a=[],b;for(b in this._ctn)a.push(b);return a},values:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);return a},toString:k.uber.toString};var e=function(a){f.apply(this,arguments);this.pushRange(a)};g(e,f);e.prototype={size:e.uber.size,clear:e.uber.clear,push:e.uber.set,pushRange:e.uber.setRange,contains:e.uber.contains,
empty:e.uber.empty,toString:e.uber.toString,pop:function(){return this._ctn.pop()},peek:function(){return this._ctn[this.size()-1]},toArray:function(){for(var a=[],b=this.size()-1;0<=b;b--)a.push(this._ctn[b]);return a},each:function(a){if("function"===typeof a)for(;!this.empty()&&!1!==a(this.pop()););}};var d=function(a){f.apply(this,arguments);this.offerRange(a)};g(d,f);d.prototype={size:d.uber.size,clear:d.uber.clear,offer:d.uber.set,offerRange:d.uber.setRange,contains:d.uber.contains,empty:d.uber.empty,
toArray:d.uber.toArray,toString:d.uber.toString,poll:function(){return this._ctn.shift()},peek:function(){return this._ctn[0]},each:function(a){if("function"===typeof a)for(;!this.empty()&&!1!==a(this.poll()););}};window.List=c;window.Map=k;window.Stack=e;window.Queue=d})();
