/* Elijah JavaScript Collection Library v0.9 Copyright 2013 Simon P Chang. */
(function(){function l(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.b=b.prototype}Object.prototype.toString=function(){var a=[],b;for(b in this)a.push(b+":"+(null===this[b]?"null":this[b].toString()));return"{"+a.join(",")+"}"};Array.prototype.toString=function(){var a=[],b;for(b in this)a.push(null===this[b]?"null":this[b].toString());return"["+a.join(",")+"]"};Date.prototype.toString=function(){return this.getMonth()+1+"/"+this.getDate()+"/"+this.getFullYear()+
" "+this.getHours()+":"+this.getMinutes()+":"+this.getSeconds()+"."+this.getMilliseconds()};String.prototype.toString=function(){return"'"+this+"'"};var p=function(){this._ctn};p.prototype={toString:function(){return this._ctn.toString()}};var m=function(){p.apply(this,arguments);this._ctn=[]};l(m,p);m.prototype={size:function(){return this._ctn.length},clear:function(){delete this._ctn;this._ctn=[]},set:function(a){void 0!==a&&this._ctn.push(a)},setRange:function(a){a instanceof Array&&a.length?
this._ctn=this._ctn.concat(a):a instanceof List&&(a.size&&a.size())&&(this._ctn=this._ctn.concat(a._ctn))},contains:function(a){return-1!==this._ctn.indexOf(a)},empty:function(){return 0===this.size()},toArray:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);return a},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(parseInt(b,10),this._ctn[b]))break},toString:m.b.toString};var n=function(){p.apply(this,arguments);this._ctn={};this._size=0};l(n,p);n.prototype=
{size:function(){return this._size},clear:function(){delete this._ctn;this._ctn={};this._size=0},get:function(a){return this._ctn[a]},containsKey:function(a){for(var b in this._ctn)if(b===a)return!0;return!1},remove:function(a){void 0!==a&&(delete this._ctn[a],this._size--)},removeByValue:function(a){for(var b in this._ctn)this._ctn[b]===a&&this.remove(b)},empty:function(){return 0===this._size},keys:function(){var a=[],b;for(b in this._ctn)a.push(b);return a},values:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);
return a},toString:n.b.toString};var f=function(a){m.apply(this,arguments);this.setRange(a)};l(f,m);f.prototype={size:f.b.size,clear:f.b.clear,set:f.b.set,get:function(a){return this._ctn[a]},setRange:f.b.setRange,insert:function(a,b){0<=a&&a<=this.size()&&void 0!==b&&this._ctn.splice(a,0,b)},insertRange:function(a,b){var c;b instanceof Array&&b.length?c=b:b instanceof List&&(b.size&&b.size())&&(c=b._ctn);if(c)for(var d=c.length;d--;)this.insert(a,c[d])},contains:f.b.contains,indexOf:function(a){return this._ctn.indexOf(a)},
lastIndexOf:function(a){return this._ctn.lastIndexOf(a)},indicesOf:function(a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(parseInt(c,10));return b},empty:f.b.empty,removeAt:function(a){0<=a&&a<this.size()&&this._ctn.splice(a,1)},removeRange:function(a,b){0<=a&&a<b&&this._ctn.splice(a,b-a)},remove:function(a){this.removeAt(this.indexOf(a))},removeLast:function(a){this.removeAt(this.lastIndexOf(a))},removeAll:function(a){if(void 0===a)this.clear();else for(var b=this.size();b--;)this._ctn[b]===
a&&this.removeAt(b)},reverse:function(){this._ctn.reverse()},sub:function(a,b){if(0<=a&&b<=this.size()){for(var c=new List;a<b;)c.set(this._ctn[a++]);return c}},toArray:f.b.toArray,each:f.b.each,filter:function(a){if("function"===typeof a){var b=new f,c;for(c in this._ctn)!0===a(parseInt(c,10),this._ctn[c])&&b.set(this._ctn[c]);return b}},toString:f.b.toString};var e=function(){n.apply(this,arguments)};l(e,n);e.prototype={size:e.b.size,clear:e.b.clear,set:function(a,b){void 0!==a&&void 0!==b&&(void 0===
this._ctn[a]&&this._size++,this._ctn[a]=b)},get:e.b.get,getByValue:function(a){if(void 0!==a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(c);return b}},containsKey:e.b.containsKey,containsValue:function(a){for(var b in this._ctn)if(this._ctn[b]===a)return!0;return!1},remove:e.b.remove,removeByValue:e.b.removeByValue,empty:e.b.empty,each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(b,this._ctn[b]))break},filter:function(a){if("function"===typeof a){var b=new e,c;
for(c in this._ctn)!0===a(c,this._ctn[c])&&b.set(c,this._ctn[c]);return b}},keys:e.b.keys,values:e.b.values,toString:e.b.toString};var k=function(a){m.apply(this,arguments);this.pushRange(a)};l(k,m);k.prototype={size:k.b.size,clear:k.b.clear,push:k.b.set,pushRange:k.b.setRange,contains:k.b.contains,empty:k.b.empty,toString:k.b.toString,pop:function(){return this._ctn.pop()},peek:function(){return this._ctn[this.size()-1]},toArray:function(){for(var a=[],b=this.size();b--;)a.push(this._ctn[b]);return a},
each:function(a){if("function"===typeof a)for(;!this.empty()&&!1!==a(this.pop()););}};var h=function(a){m.apply(this,arguments);this.offerRange(a)};l(h,m);h.prototype={size:h.b.size,clear:h.b.clear,offer:h.b.set,offerRange:h.b.setRange,contains:h.b.contains,empty:h.b.empty,toArray:h.b.toArray,toString:h.b.toString,poll:function(){return this._ctn.shift()},peek:function(){return this._ctn[0]},each:function(a){if("function"===typeof a)for(;!this.empty()&&!1!==a(this.poll()););}};var g=function(){n.apply(this,
arguments)};l(g,n);g.prototype={size:g.b.size,clear:g.b.clear,get:g.b.get,containsKey:g.b.containsKey,remove:g.b.remove,removeByValue:g.b.removeByValue,empty:g.b.empty,keys:g.b.keys,values:g.b.values,toString:g.b.toString,set:function(a,b){void 0!==a&&void 0!==b&&(void 0===this._ctn[a]&&(this._size++,this._ctn[a]=[]),-1===this._ctn[a].indexOf(b)&&this._ctn[a].push(b))},getByValue:function(a){if(void 0!==a){var b=[],c;for(c in this._ctn)-1!==this._ctn[c].indexOf(a)&&b.push(c);return b}},getNumberOfValues:function(a){if(void 0!==
a&&this._ctn[a])return this._ctn[a].length},containsValue:function(a){for(var b in this._ctn)if(-1!==this._ctn[b].indexOf(a))return!0;return!1},removeByContainsValue:function(a){for(var b in this._ctn)-1!==this._ctn[b].indexOf(a)&&this.remove(b)},removeValue:function(a){for(var b in this._ctn)var c=-1!==this._ctn[b].indexOf(a)&&(1===this._ctn[b].length?this.remove(b):this._ctn[b].splice(c,1))},each:function(a){if("function"===typeof a)for(var b in this._ctn){var c=this._ctn[b],d;for(d in c)if(!1===
a(b,c[d]))break}},filter:function(a){if("function"===typeof a){var b=new g,c;for(c in this._ctn){var d=this._ctn[c],e;for(e in d)!0===a(c,d[e])&&b.set(c,d[e])}return b}}};var d=function(){e.apply(this,arguments)};l(d,e);d.prototype={size:d.b.size,clear:d.b.clear,get:d.b.get,getByValue:d.b.getByValue,containsKey:d.b.containsKey,containsValue:d.b.containsValue,remove:d.b.remove,removeByValue:d.b.removeByValue,empty:d.b.empty,each:d.b.each,filter:d.b.each,keys:d.b.keys,values:d.b.values,toString:d.b.toString,
set:function(a,b){if(void 0!==a&&void 0!==b)if(void 0!==this._ctn[a]||0===this.size())this._ctn[a]=b,0===this.size()&&this._size++;else{var c={},d;for(d in this._ctn)d>a&&(c[a]=b),c[d]=this._ctn[d];delete this._ctn;this._ctn=c;this._size++}}};var j=function(a){f.apply(this,arguments);this.setRange(a)};l(j,f);j.prototype={size:j.b.size,clear:j.b.clear,contains:j.b.contains,empty:j.b.empty,remove:j.b.remove,toArray:j.b.toArray,toString:j.b.toString,set:function(a){function b(a){return null===a?"null":
a.toString().replace(/^'/,"").replace(/'$/,"")}if(void 0!==a&&!this.contains(a)){var c=this.size();if(0===c||b(this._ctn[c-1])<b(a))this._ctn.push(a);else for(var d in this._ctn)if(b(this._ctn[d])>b(a)){this._ctn.splice(d,0,a);break}}},setRange:function(a){var b=[];a instanceof Array&&a.length?b=a:a instanceof List&&(a.size&&a.size())&&(b=a._ctn);for(var c in b)this.set(b[c])},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(this._ctn[b]))break},filter:function(a){if("function"===
typeof a){var b=new j,c;for(c in this._ctn)!0===a(this._ctn[c])&&b.set(this._ctn[c]);return b}}};window.List=f;window.Map=e;window.Stack=k;window.Queue=h;window.MultiMap=g;window.TreeMap=d;window.TreeSet=j})();
