/* Elijah JavaScript Collection Library v1.0 Copyright 2013 Simon P Chang. */
(function(){function l(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.b=b.prototype}Object.prototype.toString=function(){var a=[],b;for(b in this)a.push(b+":"+(null===this[b]?"null":this[b].toString()));return"{"+a.join(",")+"}"};Array.prototype.toString=function(){var a=[],b;for(b in this)a.push(null===this[b]?"null":this[b].toString());return"["+a.join(",")+"]"};Date.prototype.toString=function(){return this.getMonth()+1+"/"+this.getDate()+"/"+this.getFullYear()+
" "+this.getHours()+":"+this.getMinutes()+":"+this.getSeconds()+"."+this.getMilliseconds()};String.prototype.toString=function(){return"'"+this+"'"};var q=function(){this._ctn};q.prototype={toString:function(){return this._ctn.toString()}};var n=function(){q.apply(this,arguments);this._ctn=[]};l(n,q);n.prototype={size:function(){return this._ctn.length},clear:function(){delete this._ctn;this._ctn=[]},set:function(a){void 0!==a&&this._ctn.push(a)},setRange:function(a){a instanceof Array&&a.length?
this._ctn=this._ctn.concat(a):a instanceof List&&(a.size&&a.size())&&(this._ctn=this._ctn.concat(a._ctn))},contains:function(a){return-1!==this._ctn.indexOf(a)},empty:function(){return 0===this.size()},toArray:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);return a},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(parseInt(b,10),this._ctn[b]))break},toString:n.b.toString};var p=function(){q.apply(this,arguments);this._ctn={};this._size=0};l(p,q);p.prototype=
{size:function(){return this._size},clear:function(){delete this._ctn;this._ctn={};this._size=0},get:function(a){return this._ctn[a]},containsKey:function(a){for(var b in this._ctn)if(b===a)return!0;return!1},remove:function(a){void 0!==a&&(delete this._ctn[a],this._size--)},removeByValue:function(a){for(var b in this._ctn)this._ctn[b]===a&&this.remove(b)},empty:function(){return 0===this._size},keys:function(){var a=[],b;for(b in this._ctn)a.push(b);return a},values:function(){var a=[],b;for(b in this._ctn)a.push(this._ctn[b]);
return a},toString:p.b.toString};var g=function(a){n.apply(this,arguments);this.setRange(a)};l(g,n);g.prototype={size:g.b.size,clear:g.b.clear,set:g.b.set,get:function(a){return this._ctn[a]},setRange:g.b.setRange,insert:function(a,b){0<=a&&a<=this.size()&&void 0!==b&&this._ctn.splice(a,0,b)},insertRange:function(a,b){var c;b instanceof Array&&b.length?c=b:b instanceof List&&(b.size&&b.size())&&(c=b._ctn);if(c)for(var d=c.length;d--;)this.insert(a,c[d])},contains:g.b.contains,indexOf:function(a){return this._ctn.indexOf(a)},
lastIndexOf:function(a){return this._ctn.lastIndexOf(a)},indicesOf:function(a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(parseInt(c,10));return b},empty:g.b.empty,removeAt:function(a){0<=a&&a<this.size()&&this._ctn.splice(a,1)},removeRange:function(a,b){0<=a&&a<b&&this._ctn.splice(a,b-a)},remove:function(a){this.removeAt(this.indexOf(a))},removeLast:function(a){this.removeAt(this.lastIndexOf(a))},removeAll:function(a){if(void 0===a)this.clear();else for(var b=this.size();b--;)this._ctn[b]===
a&&this.removeAt(b)},reverse:function(){this._ctn.reverse()},sub:function(a,b){if(0<=a&&b<=this.size()){for(var c=new List;a<b;)c.set(this._ctn[a++]);return c}},toArray:g.b.toArray,each:g.b.each,filter:function(a){if("function"===typeof a){var b=new g,c;for(c in this._ctn)!0===a(parseInt(c,10),this._ctn[c])&&b.set(this._ctn[c]);return b}},toString:g.b.toString};var d=function(){p.apply(this,arguments)};l(d,p);d.prototype={size:d.b.size,clear:d.b.clear,set:function(a,b){void 0!==a&&void 0!==b&&(this.containsKey(a)||
this._size++,this._ctn[a]=b)},get:d.b.get,getByValue:function(a){if(void 0!==a){var b=[],c;for(c in this._ctn)this._ctn[c]===a&&b.push(c);return b}},containsKey:d.b.containsKey,containsValue:function(a){for(var b in this._ctn)if(this._ctn[b]===a)return!0;return!1},remove:d.b.remove,removeByValue:d.b.removeByValue,empty:d.b.empty,each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(b,this._ctn[b]))break},filter:function(a){if("function"===typeof a){var b=new d,c;for(c in this._ctn)!0===
a(c,this._ctn[c])&&b.set(c,this._ctn[c]);return b}},keys:d.b.keys,values:d.b.values,toString:d.b.toString};var m=function(a){n.apply(this,arguments);this.pushRange(a)};l(m,n);m.prototype={size:m.b.size,clear:m.b.clear,push:m.b.set,pushRange:m.b.setRange,contains:m.b.contains,empty:m.b.empty,toString:m.b.toString,pop:function(){return this._ctn.pop()},peek:function(){return this._ctn[this.size()-1]},toArray:function(){for(var a=[],b=this.size();b--;)a.push(this._ctn[b]);return a},each:function(a){if("function"===
typeof a)for(;!this.empty()&&!1!==a(this.pop()););}};var j=function(a){n.apply(this,arguments);this.offerRange(a)};l(j,n);j.prototype={size:j.b.size,clear:j.b.clear,offer:j.b.set,offerRange:j.b.setRange,contains:j.b.contains,empty:j.b.empty,toArray:j.b.toArray,toString:j.b.toString,poll:function(){return this._ctn.shift()},peek:function(){return this._ctn[0]},each:function(a){if("function"===typeof a)for(;!this.empty()&&!1!==a(this.poll()););}};var h=function(){p.apply(this,arguments)};l(h,p);h.prototype=
{size:h.b.size,clear:h.b.clear,get:h.b.get,containsKey:h.b.containsKey,remove:h.b.remove,removeByValue:h.b.removeByValue,empty:h.b.empty,keys:h.b.keys,values:h.b.values,toString:h.b.toString,set:function(a,b){void 0!==a&&void 0!==b&&(void 0===this._ctn[a]&&(this._size++,this._ctn[a]=[]),-1===this._ctn[a].indexOf(b)&&this._ctn[a].push(b))},getByValue:function(a){if(void 0!==a){var b=[],c;for(c in this._ctn)-1!==this._ctn[c].indexOf(a)&&b.push(c);return b}},getNumberOfValues:function(a){if(void 0!==
a&&this._ctn[a])return this._ctn[a].length},containsValue:function(a){for(var b in this._ctn)if(-1!==this._ctn[b].indexOf(a))return!0;return!1},removeByContainsValue:function(a){for(var b in this._ctn)-1!==this._ctn[b].indexOf(a)&&this.remove(b)},removeValue:function(a){for(var b in this._ctn)var c=-1!==this._ctn[b].indexOf(a)&&(1===this._ctn[b].length?this.remove(b):this._ctn[b].splice(c,1))},each:function(a){if("function"===typeof a)for(var b in this._ctn){var c=this._ctn[b],d;for(d in c)if(!1===
a(b,c[d]))break}},filter:function(a){if("function"===typeof a){var b=new h,c;for(c in this._ctn){var d=this._ctn[c],e;for(e in d)!0===a(c,d[e])&&b.set(c,d[e])}return b}}};var e=function(){d.apply(this,arguments)};l(e,d);e.prototype={size:e.b.size,clear:e.b.clear,get:e.b.get,getByValue:e.b.getByValue,containsKey:e.b.containsKey,containsValue:e.b.containsValue,remove:e.b.remove,removeByValue:e.b.removeByValue,empty:e.b.empty,each:e.b.each,filter:e.b.each,keys:e.b.keys,values:e.b.values,toString:e.b.toString,
set:function(a,b){if(void 0!==a&&void 0!==b)if(void 0!==this._ctn[a]||0===this.size())this._ctn[a]=b,0===this.size()&&this._size++;else{var c={},d;for(d in this._ctn)d>a&&(c[a]=b),c[d]=this._ctn[d];delete this._ctn;this._ctn=c;this._size++}}};var k=function(a){g.apply(this,arguments);this.setRange(a)};l(k,g);k.prototype={size:k.b.size,clear:k.b.clear,contains:k.b.contains,empty:k.b.empty,remove:k.b.remove,toArray:k.b.toArray,toString:k.b.toString,set:function(a){function b(a){return null===a?"null":
a.toString().replace(/^'/,"").replace(/'$/,"")}if(void 0!==a&&!this.contains(a)){var c=this.size();if(0===c||b(this._ctn[c-1])<b(a))this._ctn.push(a);else for(var d in this._ctn)if(b(this._ctn[d])>b(a)){this._ctn.splice(d,0,a);break}}},setRange:function(a){var b=[];a instanceof Array&&a.length?b=a:a instanceof List&&(a.size&&a.size())&&(b=a._ctn);for(var c in b)this.set(b[c])},each:function(a){if("function"===typeof a)for(var b in this._ctn)if(!1===a(this._ctn[b]))break},filter:function(a){if("function"===
typeof a){var b=new k,c;for(c in this._ctn)!0===a(this._ctn[c])&&b.set(this._ctn[c]);return b}}};var f=function(){d.apply(this,arguments)};l(f,d);f.prototype={size:f.b.size,clear:f.b.clear,get:f.b.get,containsKey:f.b.containsKey,containsValue:f.b.containsValue,remove:f.b.remove,removeByValue:f.b.removeByValue,empty:f.b.empty,each:f.b.each,filter:f.b.filter,keys:f.b.keys,values:f.b.values,toString:f.b.toString,set:function(a,b){void 0===a||void 0===b||this.containsKey(a)||this.containsValue(b)||(this._ctn[a]=
b,this._size++)},getByValue:function(a){if(void 0!==a){var b,c;for(c in this._ctn)this._ctn[c]===a&&(b=c);return b}}};window.List=g;window.Map=d;window.Stack=m;window.Queue=j;window.MultiMap=h;window.TreeMap=e;window.TreeSet=k;window.BiMap=f})();
